name: Run code from 2021.08.12

on:
  push:
    branches: [ main ]
  
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Run
      working-directory: "20210812"
      run: |
        dotnet run
      


